name: Test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Test solutions day01p1
        run: cd day01p1 && go test -cover

      - name: Test solutions day01p2
        run: cd day01p2 && go test -cover